### ISSUE TITLE
在编辑页面，多规格的规格名的数量大于2个时候，从第3个开始渲染不出来

### ISSUE THREAD

**Issue by beautycss** [fingerQin/sku#1]
**操作：**
添加多规格的时候，添加了3个规格名，规格值也填好了，保存到数据库里的也是3个规格名和对应的规格值。

**问题：**
编辑的时候，只出来了两个规格名，第3个规格名和对应的规格值都没出来，整个table少了第3个tr。

**解决方案：**
`sku.js`的147行目前代码：
```
tr.find('td:eq(2) .Js_add_attr_name').trigger('click');
```
需要修改成：
```
tbody.find('tr:eq(0)').find('td:eq(2) .Js_add_attr_name').trigger('click');
```

**问题原因**
添加按钮只在第一个tr的第3个td里面有，修改之后就好了。

**Comment by fingerQin** [comment]
兄弟，你测过没有。测过我直接优化升级了。

**Comment by beautycss** [comment]
> 兄弟，你测过没有。测过我直接优化升级了。

测过没问题的，可以升级。
view里的php我都看了，第2条数据能渲染出来是因为php的tbody里默认有一个tr，这个tr最后一个td里就是添加按钮，所以第1个和第2个能正常渲染出来，只要大于第2个就渲染不出来。
因为只有第一个tr里有添加按钮，后面的tr里都只有删除按钮，没有添加按钮。

**Comment by fingerQin** [comment]
OK。已处理。

**Comment by beautycss** [comment]
> OK。已处理。

给你这速度点赞。
其他几个fork出来的组件也有这个问题，但是有的不能提issue，我也没空拉下来然后去提pr。我是今天多添加了一个规格名，突然发现这个问题的。
我之前用的另外一个fork出来的sku组件，但是点击单规格按钮啥都没有，出不来价格和库存输入框，你这个就可以正常出来没问题。
